name: Build VC6 Toolchain

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build-vc6:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Create the downloads directory
      run: |
        mkdir downloads

    - name: Cache downloaded files
      uses: actions/cache@v4
      id: cache-downloads
      with:
        key: file-downloads-v1-${{ hashFiles('downloads.txt') }}
        path: |
          downloads

    - name: Download files
      if: steps.cache-downloads.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        Get-Content downloads.txt | ForEach-Object {
          $url = $_
          $filename = "downloads\" + [System.IO.Path]::GetFileName($url)
          Invoke-WebRequest -Uri $url -OutFile $filename
        }

    - name: Extract files
      run: |
        python extract.py

    - name: Build VC6 Toolchain
      run: |
        python build_vc6.py

    - name: Build DirectX
      run: |
        .\build_dx.ps1

    - name: Package
      run: |
        .\package.ps1

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/DirectX81SDK.7z
          build/VC6.7z
