name: Build VC6 Toolchain

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-vc6:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4

    - name: Create the downloads directory
      run: |
        mkdir downloads

    - name: Cache downloaded files
      uses: actions/cache@v4
      id: cache-downloads
      with:
        key: file-downloads-v1-${{ hashFiles('downloads.txt') }}
        path: |
          downloads

    - name: Download files
      if: ${{ steps.cache-downloads.outputs.cache-hit != 'true' }}
      shell: powershell
      run: |
        Get-Content downloads.txt | ForEach-Object {
          $url = $_
          $filename = "downloads\" + [System.IO.Path]::GetFileName($url)
          Invoke-WebRequest -Uri $url -OutFile $filename
        }

    - name: Extract files
      run: |
        python extract.py

    - name: Patch and Install Visual Studio 6.0
      run: |
        patch --strip=0 --input=vs98ent.stf.patch
        cd extract\VS6CD\SETUP
        echo ".\ACMSETUP.EXE /T ${{ github.workspace }}\VS98ENT.STF /Q T /K 1111111111 /S ${{ github.workspace }}\extract\VS6CD"
        .\ACMSETUP.EXE /T ${{ github.workspace }}\VS98ENT.STF /Q T /K 1111111111 /S ${{ github.workspace }}\extract\VS6CD

        # Now wait for the process to finish running, looking for ACMSETUP.EXE
        Write-Host "Waiting for ACMSETUP.EXE to complete..."
        while (Get-Process -Name "ACMSETUP" -ErrorAction SilentlyContinue) {
            Write-Host "Installation in progress..."
            Start-Sleep -Seconds 15
        }
        Write-Host "Installation completed."
        
        dir "C:\Program Files (x86)\Microsoft Visual Studio\"

    - name: Install Service Pack 6
      run: |
        cd extract\VS6SP6
        .\ACMSETUP.EXE /T sp698ent.stf /Q T /S ${{ github.workspace }}\extract\VS6SP6
        Write-Host "Waiting for ACMSETUP.EXE to complete..."
        while (Get-Process -Name "ACMSETUP" -ErrorAction SilentlyContinue) {
            Write-Host "Installation in progress..."
            Start-Sleep -Seconds 15
        }
        Write-Host "Installation completed."

#    - name: Download Visual Studio 6.0 Enterprise Edition
#      if: ${{ steps.cache-downloads.outputs.cache-hit != 'true' }}
#      run: |
#        curl -L "https://archive.org/download/en_vs6_ent/en_vs6_ent_cd1.iso" -o downloads/en_vs6_ent_cd1.iso

# https://archive.org/download/dx81b_sdk/DX81b_SDK.exe
# 7z.exe x DX81b_SDK.exe

# https://archive.org/download/en_vs6_ent/en_vs6_sp6.exe
# en_vs6_sp6.exe /T:C:\ABS\Path\To\Extraction\Directory /C


# ACMSETUP.EXE /T VS98ENT.STF /Q T /K 1111111111 /S C:\Users\Win10\Desktop\VS6CD

# ACMSETUP.EXE /T VS98ENT.STF /Q T /K 1111111111 /S C:\Users\Win10\Desktop\VS6CD

